/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.liftproject;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 * @author Belyaev Vitaly
 * main class of the programm. GUI and threads starts here
 */
public class GUI extends javax.swing.JFrame {
//создаем экземпляр класса лифт 1
//create example of class elevator 1
Elevator elevator1; 
//создаем экземпляр класса лифт 2
//create example of class elevator 2
Elevator elevator2; 
//создаём переменную под таблицу журнала 
//create var for table of journal
DefaultTableModel journal;
//создаём переменную под таблицу тикетов 
////create var for table of tikets
DefaultTableModel tiketsTable;
//создаем переменную под игровое время которую будет обновлять TimeThread.java
//create var for game time. This var will be changing from TimeThread.java
public static String gameTime;
//создаем экземляр класса ticketManager который делает краткоживущие ордеры из тикетов и управлеят тикетами
//create example of class ticketManager. The class will be making orders from tikets and will manage of all tikects 
TicketsManager ticketManager; 
//инициализируем экземпляр класса через который будем синхронизировать ордера между тремя потоками (Elevator1Thread,Elevator2Thread и TiketsManagerThread)
//Initialization of example class  syncListOrders. The class will using for synhronized betwin three threads (Elevator1Thread,Elevator2Thread и TiketsManagerThread)
SyncListOrders syncListOrders = new SyncListOrders();
    /**
     * Инициалиция компонетов с гуёвой формы
     * Initialization GUI components
     */
    public GUI() {
        initComponents();
        //Присваиваем переменной журнала инициализированный компонент-таблицу играющую роль журнала
        //Assign the initialized component to the log variable-the table that plays the role of the log
        journal = (DefaultTableModel)TableOfJournal.getModel();       
        //Присваиваем переменной таблицы тикетов инициализированный компонент-таблицу тикетов
        //Assign the initialized component of GUI to the var tiketsTable
        tiketsTable = (DefaultTableModel)TableOfOrders.getModel();      
        //Помещаем текстбоксы первой колонки в массив для лучшего управления. Это шахта лифта 1
        //Put on all textboxes of first column into array for comfort work. It will be elevator shaft number 1 
        javax.swing.JTextField arrayLiftMine1[] =new javax.swing.JTextField[]{L10,L11,L12,L13,L14,L15,L16,L17,L18,L19,L110,L111,L112,L113};
        //Инициализируем лифт 1.
        //Initialization elevator1
        elevator1 = new Elevator(1,arrayLiftMine1,syncListOrders.returnListOrders(),journal);
        //Помещаем текстбоксы второй колонки в массив для лучшего управления. Это шахта лифта 2
        //Put on all textboxes of second column into array for comfort work. It will be elevator shaft number 2 
        javax.swing.JTextField arrayLiftMine2[] =new javax.swing.JTextField[]{L20,L21,L22,L23,L24,L25,L26,L27,L28,L29,L210,L211,L212,L213} ;
        //Инициализируем лифт 2. Передаём ему массив текстбоксов которые являются шахтой лифта,синхронизированные  ордера и журнал
        //Initialization elevator2
        elevator2 = new Elevator(2,arrayLiftMine2,syncListOrders.returnListOrders(),journal);
        //Инициализируем TikectsManager. 
        //Initialization TikectsManager
        ticketManager= new TicketsManager(tiketsTable,syncListOrders.returnListOrders(),journal,elevator1,elevator2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L10 = new javax.swing.JTextField();
        L11 = new javax.swing.JTextField();
        L12 = new javax.swing.JTextField();
        L13 = new javax.swing.JTextField();
        L14 = new javax.swing.JTextField();
        L15 = new javax.swing.JTextField();
        L16 = new javax.swing.JTextField();
        L17 = new javax.swing.JTextField();
        L18 = new javax.swing.JTextField();
        L19 = new javax.swing.JTextField();
        L110 = new javax.swing.JTextField();
        L111 = new javax.swing.JTextField();
        L112 = new javax.swing.JTextField();
        L113 = new javax.swing.JTextField();
        L20 = new javax.swing.JTextField();
        L21 = new javax.swing.JTextField();
        L22 = new javax.swing.JTextField();
        L23 = new javax.swing.JTextField();
        L24 = new javax.swing.JTextField();
        L25 = new javax.swing.JTextField();
        L26 = new javax.swing.JTextField();
        L27 = new javax.swing.JTextField();
        L28 = new javax.swing.JTextField();
        L29 = new javax.swing.JTextField();
        L210 = new javax.swing.JTextField();
        L211 = new javax.swing.JTextField();
        L212 = new javax.swing.JTextField();
        L213 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TimeTickerLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableOfJournal = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableOfOrders = new javax.swing.JTable();
        UpButton1 = new javax.swing.JButton();
        UpButton2 = new javax.swing.JButton();
        UpButton3 = new javax.swing.JButton();
        UpButton4 = new javax.swing.JButton();
        UpButton5 = new javax.swing.JButton();
        UpButton6 = new javax.swing.JButton();
        UpButton7 = new javax.swing.JButton();
        UpButton8 = new javax.swing.JButton();
        UpButton9 = new javax.swing.JButton();
        UpButton10 = new javax.swing.JButton();
        UpButton12 = new javax.swing.JButton();
        UpButton11 = new javax.swing.JButton();
        DownButton1 = new javax.swing.JButton();
        DownButton2 = new javax.swing.JButton();
        DownButton7 = new javax.swing.JButton();
        DownButton3 = new javax.swing.JButton();
        DownButton4 = new javax.swing.JButton();
        DownButton5 = new javax.swing.JButton();
        DownButton6 = new javax.swing.JButton();
        DownButton9 = new javax.swing.JButton();
        DownButton8 = new javax.swing.JButton();
        DownButton10 = new javax.swing.JButton();
        DownButton11 = new javax.swing.JButton();
        DownButton12 = new javax.swing.JButton();
        UpButton0 = new javax.swing.JButton();
        DownButton13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        L10.setEditable(false);
        L10.setText("Floor 0  ");

        L11.setEditable(false);
        L11.setText("Floor 1  ");

        L12.setEditable(false);
        L12.setText("Floor 2  ");

        L13.setEditable(false);
        L13.setText("Floor 3  ");

        L14.setEditable(false);
        L14.setText("Floor 4  ");

        L15.setEditable(false);
        L15.setText("Floor 5  ");

        L16.setEditable(false);
        L16.setText("Floor 6  ");

        L17.setEditable(false);
        L17.setText("Floor 7  ");

        L18.setEditable(false);
        L18.setText("Floor 8  ");

        L19.setEditable(false);
        L19.setText("Floor 9  ");

        L110.setEditable(false);
        L110.setText("Floor 10");
        L110.setToolTipText("");

        L111.setEditable(false);
        L111.setText("Floor 11");

        L112.setEditable(false);
        L112.setText("Floor 12");

        L113.setEditable(false);
        L113.setText("Floor 13");

        L20.setEditable(false);
        L20.setText("Floor 0  ");
        L20.setToolTipText("");

        L21.setEditable(false);
        L21.setText("Floor 1  ");
        L21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L21ActionPerformed(evt);
            }
        });

        L22.setEditable(false);
        L22.setText("Floor 2  ");
        L22.setToolTipText("");
        L22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L22ActionPerformed(evt);
            }
        });

        L23.setEditable(false);
        L23.setText("Floor 3  ");

        L24.setEditable(false);
        L24.setText("Floor 4  ");

        L25.setEditable(false);
        L25.setText("Floor 5  ");
        L25.setToolTipText("");

        L26.setEditable(false);
        L26.setText("Floor 6  ");

        L27.setEditable(false);
        L27.setText("Floor 7  ");

        L28.setEditable(false);
        L28.setText("Floor 8  ");

        L29.setEditable(false);
        L29.setText("Floor 9  ");
        L29.setToolTipText("");

        L210.setEditable(false);
        L210.setText("Floor 10");

        L211.setEditable(false);
        L211.setText("Floor 11");

        L212.setEditable(false);
        L212.setText("Floor 12");

        L213.setEditable(false);
        L213.setText("Floor 13");

        jLabel1.setText("Elevator #1");

        jLabel2.setText("Elevator #2");

        jLabel3.setText("Game time:");

        TimeTickerLabel.setText("2022-02-");
        TimeTickerLabel.setToolTipText("");

        TableOfJournal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Game time", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableOfJournal);

        TableOfOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "№ ticket's", "State", "Time start's", "Duration time's", "From", "To", "Elevator №", "Direction"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TableOfOrders);

        UpButton1.setText("△");
        UpButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpButton1ActionPerformed(evt);
            }
        });

        UpButton2.setText("△");
        UpButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpButton2ActionPerformed(evt);
            }
        });

        UpButton3.setText("△");
        UpButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpButton3ActionPerformed(evt);
            }
        });

        UpButton4.setText("△");
        UpButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpButton4ActionPerformed(evt);
            }
        });

        UpButton5.setText("△");
        UpButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpButton5ActionPerformed(evt);
            }
        });

        UpButton6.setText("△");
        UpButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpButton6ActionPerformed(evt);
            }
        });

        UpButton7.setText("△");
        UpButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpButton7ActionPerformed(evt);
            }
        });

        UpButton8.setText("△");
        UpButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpButton8ActionPerformed(evt);
            }
        });

        UpButton9.setText("△");
        UpButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpButton9ActionPerformed(evt);
            }
        });

        UpButton10.setText("△");
        UpButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpButton10ActionPerformed(evt);
            }
        });

        UpButton12.setText("△");
        UpButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpButton12ActionPerformed(evt);
            }
        });

        UpButton11.setText("△");
        UpButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpButton11ActionPerformed(evt);
            }
        });

        DownButton1.setText("▽");
        DownButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownButton1ActionPerformed(evt);
            }
        });

        DownButton2.setText("▽");
        DownButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownButton2ActionPerformed(evt);
            }
        });

        DownButton7.setText("▽");
        DownButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownButton7ActionPerformed(evt);
            }
        });

        DownButton3.setText("▽");
        DownButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownButton3ActionPerformed(evt);
            }
        });

        DownButton4.setText("▽");
        DownButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownButton4ActionPerformed(evt);
            }
        });

        DownButton5.setText("▽");
        DownButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownButton5ActionPerformed(evt);
            }
        });

        DownButton6.setText("▽");
        DownButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownButton6ActionPerformed(evt);
            }
        });

        DownButton9.setText("▽");
        DownButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownButton9ActionPerformed(evt);
            }
        });

        DownButton8.setText("▽");
        DownButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownButton8ActionPerformed(evt);
            }
        });

        DownButton10.setText("▽");
        DownButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownButton10ActionPerformed(evt);
            }
        });

        DownButton11.setText("▽");
        DownButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownButton11ActionPerformed(evt);
            }
        });

        DownButton12.setText("▽");
        DownButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownButton12ActionPerformed(evt);
            }
        });

        UpButton0.setText("△");
        UpButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpButton0ActionPerformed(evt);
            }
        });

        DownButton13.setText("▽");
        DownButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(L112, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpButton12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DownButton12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L212, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(L110, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpButton10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DownButton10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L210, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(L19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DownButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(L18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DownButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(L17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DownButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(L16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DownButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(L15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DownButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(L14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DownButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(L13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DownButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(L12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UpButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DownButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(L22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(L113, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DownButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(L111, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(UpButton11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DownButton11)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(L211, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(L213, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(L11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(UpButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(DownButton1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(L10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(UpButton0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(L20)
                                    .addComponent(L21))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TimeTickerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(289, 289, 289)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TimeTickerLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L113, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L213, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DownButton13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L212, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(L112, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(UpButton12)
                                .addComponent(DownButton12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L111, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L211, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpButton11)
                            .addComponent(DownButton11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L110, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L210, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpButton10)
                            .addComponent(DownButton10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpButton9)
                            .addComponent(DownButton9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpButton8)
                            .addComponent(DownButton8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpButton7)
                            .addComponent(DownButton7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpButton6)
                            .addComponent(DownButton6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpButton5)
                            .addComponent(DownButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpButton4)
                            .addComponent(DownButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpButton3)
                            .addComponent(DownButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpButton2)
                            .addComponent(DownButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpButton1)
                            .addComponent(DownButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpButton0)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //обработчик события кнопки вверх этажа 0
    //handler for the up floor button event 0
    private void UpButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpButton0ActionPerformed
        int currentFlor=0;
        ticketManager.addNewTicketForButton(gameTime,currentFlor,"Up");
    }//GEN-LAST:event_UpButton0ActionPerformed
    //обработчик события кнопки вверх  этажа 1
    //handler for the up floor button event 1
    private void UpButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpButton1ActionPerformed
        int currentFlor=1;
        ticketManager.addNewTicketForButton(gameTime,currentFlor,"Up");
    }//GEN-LAST:event_UpButton1ActionPerformed
    //обработчик события кнопки вверх  этажа 2
    //handler for the up floor button event 2
    private void UpButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpButton2ActionPerformed
        int currentFlor=2;
        ticketManager.addNewTicketForButton(gameTime,currentFlor,"Up");
    }//GEN-LAST:event_UpButton2ActionPerformed
    //обработчик события кнопки вверх  этажа 3
    //handler for the up floor button event 3
    private void UpButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpButton3ActionPerformed
        int currentFlor=3;
        ticketManager.addNewTicketForButton(gameTime,currentFlor,"Up");
    }//GEN-LAST:event_UpButton3ActionPerformed
    //обработчик события кнопки вверх  этажа 4
    //handler for the up floor button event 4
    private void UpButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpButton4ActionPerformed
        int currentFlor=4;
        ticketManager.addNewTicketForButton(gameTime,currentFlor,"Up");
    }//GEN-LAST:event_UpButton4ActionPerformed
    //обработчик события кнопки вверх  этажа 5
    //handler for the up floor button event 5
    private void UpButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpButton5ActionPerformed
        int currentFlor=5;
        ticketManager.addNewTicketForButton(gameTime,currentFlor,"Up");
    }//GEN-LAST:event_UpButton5ActionPerformed
    //обработчик события кнопки вверх  этажа 6
    //handler for the up floor button event 6
    private void UpButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpButton6ActionPerformed
        int currentFlor=6;
        ticketManager.addNewTicketForButton(gameTime,currentFlor,"Up");
    }//GEN-LAST:event_UpButton6ActionPerformed
    //обработчик события кнопки вверх  этажа 7
    //handler for the up floor button event 7
    private void UpButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpButton7ActionPerformed
        int currentFlor=7;
        ticketManager.addNewTicketForButton(gameTime,currentFlor,"Up");
    }//GEN-LAST:event_UpButton7ActionPerformed
//обработчик события кнопки вверх  этажа 8
    //handler for the up floor button event 8
    private void UpButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpButton8ActionPerformed
        int currentFlor=8;
        ticketManager.addNewTicketForButton(gameTime,currentFlor,"Up");
    }//GEN-LAST:event_UpButton8ActionPerformed
    //обработчик события кнопки вверх  этажа 9
    //handler for the up floor button event 9
    private void UpButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpButton9ActionPerformed
        int currentFlor=9;
        ticketManager.addNewTicketForButton(gameTime,currentFlor,"Up");
    }//GEN-LAST:event_UpButton9ActionPerformed
    //обработчик события кнопки вверх  этажа 10
    //handler for the up floor button event 10
    private void UpButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpButton10ActionPerformed
        int currentFlor=10;
        ticketManager.addNewTicketForButton(gameTime,currentFlor,"Up");
    }//GEN-LAST:event_UpButton10ActionPerformed
    //обработчик события кнопки вверх  этажа 11
    //handler for the up floor button event 11
    private void UpButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpButton11ActionPerformed
        int currentFlor=11;
        ticketManager.addNewTicketForButton(gameTime,currentFlor,"Up");
    }//GEN-LAST:event_UpButton11ActionPerformed
    //обработчик события кнопки вверх  этажа 12
    //handler for the up floor button event 12
    private void UpButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpButton12ActionPerformed
        int currentFlor=12;
        ticketManager.addNewTicketForButton(gameTime,currentFlor,"Up");
    }//GEN-LAST:event_UpButton12ActionPerformed
    //обработчик события кнопки вниз  этажа 12
    //handler for the down floor button event 12
    private void DownButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownButton12ActionPerformed
        int currentFlor=12;
        ticketManager.addNewTicketForButton(gameTime,currentFlor,"Down");
    }//GEN-LAST:event_DownButton12ActionPerformed
    //обработчик события кнопки вниз  этажа 11
    //handler for the down floor button event 11
    private void DownButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownButton11ActionPerformed
        int currentFlor=11;
        ticketManager.addNewTicket(gameTime, generationToFloorDown(currentFlor), currentFlor);
    }//GEN-LAST:event_DownButton11ActionPerformed
    //обработчик события кнопки вниз  этажа 10
    //handler for the down floor button event 10
    private void DownButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownButton10ActionPerformed
        int currentFlor=10;
        ticketManager.addNewTicketForButton(gameTime,currentFlor,"Down");
    }//GEN-LAST:event_DownButton10ActionPerformed
    //обработчик события кнопки вниз  этажа 9
    //handler for the down floor button event 9
    private void DownButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownButton9ActionPerformed
        int currentFlor=9;
        ticketManager.addNewTicketForButton(gameTime,currentFlor,"Down");
    }//GEN-LAST:event_DownButton9ActionPerformed
    //обработчик события кнопки вниз  этажа 8
    //handler for the down floor button event 8
    private void DownButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownButton8ActionPerformed
        int currentFlor=8;
        ticketManager.addNewTicketForButton(gameTime,currentFlor,"Down");
    }//GEN-LAST:event_DownButton8ActionPerformed
    //обработчик события кнопки вниз  этажа 7
    //handler for the down floor button event 7
    private void DownButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownButton7ActionPerformed
        int currentFlor=7;
        ticketManager.addNewTicketForButton(gameTime,currentFlor,"Down");
    }//GEN-LAST:event_DownButton7ActionPerformed
    //обработчик события кнопки вниз  этажа 6
    //handler for the down floor button event 6
    private void DownButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownButton6ActionPerformed
        int currentFlor=6;
        ticketManager.addNewTicket(gameTime, generationToFloorDown(currentFlor), currentFlor);
    }//GEN-LAST:event_DownButton6ActionPerformed
    //обработчик события кнопки вниз  этажа 5
    //handler for the down floor button event 5
    private void DownButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownButton5ActionPerformed
        int currentFlor=5;
        ticketManager.addNewTicketForButton(gameTime,currentFlor,"Down");
    }//GEN-LAST:event_DownButton5ActionPerformed
    //обработчик события кнопки вниз  этажа 4
    //handler for the down floor button event 4
    private void DownButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownButton4ActionPerformed
        int currentFlor=4;
        ticketManager.addNewTicketForButton(gameTime,currentFlor,"Down");
    }//GEN-LAST:event_DownButton4ActionPerformed
    //обработчик события кнопки вниз  этажа 3
    //handler for the down floor button event 3
    private void DownButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownButton3ActionPerformed
        int currentFlor=3;
        ticketManager.addNewTicketForButton(gameTime,currentFlor,"Down");
    }//GEN-LAST:event_DownButton3ActionPerformed
    //обработчик события кнопки вниз  этажа 2
    //handler for the down floor button event 2
    private void DownButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownButton2ActionPerformed
        int currentFlor=2;
        ticketManager.addNewTicketForButton(gameTime,currentFlor,"Down");
    }//GEN-LAST:event_DownButton2ActionPerformed
    //обработчик события кнопки вниз  этажа 1
    //handler for the down floor button event 1
    private void DownButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownButton1ActionPerformed
        int currentFlor=1;
        ticketManager.addNewTicketForButton(gameTime,currentFlor,"Down");
    }//GEN-LAST:event_DownButton1ActionPerformed

    private void L21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L21ActionPerformed

    private void L22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L22ActionPerformed
    //обработчик события кнопки вниз  этажа 13
    //handler for the down floor button event 13
    private void DownButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownButton13ActionPerformed
        int currentFlor=13;
        ticketManager.addNewTicketForButton(gameTime,currentFlor,"Down");
    }//GEN-LAST:event_DownButton13ActionPerformed
    /**
    * Сгенерировать этаж куда вверх
    * Generate floor to up
    */     
    private int generationToFloorUp(int _currentFloor){
        //int generationToFloor= (int)(_currentFloor+Math.random()*_currentFloor-13);
        int generationToFloor= rnd(_currentFloor,13);
        return generationToFloor;
    }
    /**
    * Сгенерировать этаж куда вниз
    * Generate floor to down
    */     
    private int generationToFloorDown(int _currentFloor){      
        int generationToFloor= rnd(0,_currentFloor);
        return generationToFloor;
    }
    /**
    * технический метод генерации этажа
    * Technical method of floor generation  
    */ 
    private static int rnd(int min,int max){
        max -=min;
        return (int) (Math.random()*++max)+min;
    }
   /**
    * Установить значение игрового времени в тикер-label над журналом
    * Set value of game time in tiker-label above journal
    */     
    public void setTime(String _time){
       TimeTickerLabel.setText(_time);
    }
 
    /**
    * Запускаем тикетменеджер в отдельном потоке
    * Start TiketManager in separate thread
    */     
    private void startWorkThread(){
       Thread work = new Thread(new TicketsManagerThread(ticketManager),"TickerManagerThread");
       work.start();
    }
    /**
    * Запускаем поток времени который обновляет переменную gameTime и выводит на лэйбл TimeTickerLabel.
    * Start thread of time for update var gameTime and label TimeTickerLabel
    */     
    private void starTimeThread(){
        new Thread(new TimeThread(30,TimeTickerLabel),"TimeThread").start();
    }
    /**
    * Запускаем лифт 1 в отдельном потоке
    * Start  elevator 1 in separate thread
    */     
    private void startLift1Thread(){
         new Thread(new Elevator1Thread(elevator1),"Lift1Thread").start();
    }
    /**
    * Запускаем лифт 2 в отдельном потоке
    * Start  elevator 2 in separate thread
    */     
    private void startLift2Thread(){
         new Thread(new Elevator2Thread(elevator2),"Lift2Thread").start();
    }
    /**
    * Синхронизация списка ордеров между потоками лифтов и тикетменеджером.
    * Synchronization of the list of orders between the elevator threads and the ticket manager.
    */     
    public class SyncListOrders {
       private ArrayList<orders> ListOfOrders = new ArrayList<orders>();
       public ArrayList<orders> returnListOrders() {
           synchronized (ListOfOrders) {
               //only one thread can used it
               return ListOfOrders;
           }
       }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                GUI GUI = new GUI();
                GUI.setVisible(true);
                GUI.starTimeThread();
                GUI.startWorkThread();
                GUI.startLift1Thread();
                GUI.startLift2Thread();
            }           
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DownButton1;
    private javax.swing.JButton DownButton10;
    private javax.swing.JButton DownButton11;
    private javax.swing.JButton DownButton12;
    private javax.swing.JButton DownButton13;
    private javax.swing.JButton DownButton2;
    private javax.swing.JButton DownButton3;
    private javax.swing.JButton DownButton4;
    private javax.swing.JButton DownButton5;
    private javax.swing.JButton DownButton6;
    private javax.swing.JButton DownButton7;
    private javax.swing.JButton DownButton8;
    private javax.swing.JButton DownButton9;
    private javax.swing.JTextField L10;
    private javax.swing.JTextField L11;
    private javax.swing.JTextField L110;
    private javax.swing.JTextField L111;
    private javax.swing.JTextField L112;
    private javax.swing.JTextField L113;
    private javax.swing.JTextField L12;
    private javax.swing.JTextField L13;
    private javax.swing.JTextField L14;
    private javax.swing.JTextField L15;
    private javax.swing.JTextField L16;
    private javax.swing.JTextField L17;
    private javax.swing.JTextField L18;
    private javax.swing.JTextField L19;
    private javax.swing.JTextField L20;
    private javax.swing.JTextField L21;
    private javax.swing.JTextField L210;
    private javax.swing.JTextField L211;
    private javax.swing.JTextField L212;
    private javax.swing.JTextField L213;
    private javax.swing.JTextField L22;
    private javax.swing.JTextField L23;
    private javax.swing.JTextField L24;
    private javax.swing.JTextField L25;
    private javax.swing.JTextField L26;
    private javax.swing.JTextField L27;
    private javax.swing.JTextField L28;
    private javax.swing.JTextField L29;
    private javax.swing.JTable TableOfJournal;
    private javax.swing.JTable TableOfOrders;
    private javax.swing.JLabel TimeTickerLabel;
    private javax.swing.JButton UpButton0;
    private javax.swing.JButton UpButton1;
    private javax.swing.JButton UpButton10;
    private javax.swing.JButton UpButton11;
    private javax.swing.JButton UpButton12;
    private javax.swing.JButton UpButton2;
    private javax.swing.JButton UpButton3;
    private javax.swing.JButton UpButton4;
    private javax.swing.JButton UpButton5;
    private javax.swing.JButton UpButton6;
    private javax.swing.JButton UpButton7;
    private javax.swing.JButton UpButton8;
    private javax.swing.JButton UpButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
